name: events360
description: "Events360: Your Complete Conference Companion - Navigate
  schedules, connect with speakers, and maximize your event experience."
publish_to: "none"
version: 1.0.0+3 # Format: [version].[subversion].[patch]+[build number]

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2
  path: ^1.9.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  sqflite: ^2.3.0
  supabase_flutter: ^2.8.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/.env

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi-Italic.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 600
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 500

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/cft360_logo.png"
