name: events360
description: "A simple Flutter application with a single screen displaying an image."
publish_to: "none"
version: 1.0.0+1 # Format: [version].[subversion].[patch]+[build number]

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi-Italic.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 600
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 500

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/cft360_logo.png"
